apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  selector:
    matchLabels:
      app: vproapp
  replicas: 1
  template:
    metadata:
      labels:
        app: vproapp  # Ensure consistency with metadata.labels.app
    spec:
      containers:
        - name: app
          image: vprofile/vprofileapp:V1
          ports:
            - name: app-port
              containerPort: 8080
      initContainers:
        - name: init-mq
          image: busybox
          command: ['sh', '-c', 'until nslookup vpromq01; do echo waiting for mq-server; sleep 2; done;']
        - name: init-db
          image: busybox
          command: [ 'sh', '-c', 'until nslookup vprodb; do echo waiting for db-server; sleep 2; done;' ]
