apiVersion: v1
kind: Service
metadata:
  name: svc-db
  labels:
    app: vprodb
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: vprodb
  type: ClusterIP