apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  labels:
    app: vproapp
spec:
  ports:
    - port: 80
      targetPort: app-port
      protocol: TCP
  selector:
    app: vproapp
  type: LoadBalancer