apiVersion: v1
kind: Service
metadata:
  name: svc-mc
  labels:
    app: vpromc
spec:
  ports:
    - port: 11211
      targetPort: mc-port
      protocol: TCP
  selector:
    app: vpromc
  type: ClusterIP